import { getDbColumnsFromFields } from "@/lib/entityFields/helpers";
import type { EntityFieldDefinition } from "@/lib/entityFields/types";
import type { ListDetailEntityDefinition } from "@/lib/entities/core/entityDefinition";
import type { EntityFilterDefinition } from "@/lib/search/databaseFilters";

import {
  currencyOptions,
  purchaseLineTypeOptions,
} from "@/lib/entityFields/commonOptions";

export const supplierFields: readonly EntityFieldDefinition[] = [
  {
    key: "name",
    dbName: "name",
    labelKey: "name",
    type: "text",
    required: true,
    showInList: true,
    showInForm: true,
    showInFactBox: true,
    formColSpan: "full",
  },
  {
    key: "commercial_name",
    dbName: "commercial_name",
    labelKey: "commercialName",
    type: "text",
    required: false,
    showInList: true,
    showInForm: true,
    showInFactBox: false,
    formColSpan: "full",
  },
  {
    key: "code",
    dbName: "code",
    labelKey: "code",
    type: "text",
    normalization: "uppercase",
    required: false,
    showInList: true,
    showInForm: true,
    showInFactBox: false,
  },
  {
    key: "currency_code",
    dbName: "currency_code",
    labelKey: "currency",
    type: "option",
    required: true,
    createDefaultValueFromActiveCompanyDbName: "currency_code",
    showInList: false,
    showInForm: true,
    showInFactBox: false,
    options: currencyOptions,
  },
  {
    key: "payment_channel_id",
    dbName: "payment_channel_id",
    labelKey: "paymentChannel",
    type: "select",
    required: false,
    relation: {
      entityKey: "paymentChannels",
      displayFieldName: "payment_channel_display",
      relationDataFieldName: "payment_channels",
      optionValueField: "id",
      optionLabelFieldNames: ["code"],
      labelSeparator: " - ",
      navigable: true,
    },
    showInList: false,
    showInForm: true,
    showInFactBox: false,
  },
  {
    key: "tax_id",
    dbName: "tax_id",
    labelKey: "taxId",
    type: "text",
    required: true,
    showInList: true,
    showInForm: true,
    showInFactBox: true,
  },
  {
    key: "withholding_rate",
    dbName: "withholding_rate",
    labelKey: "withholdingRate",
    type: "decimal",
    validation: "percentage",
    required: false,
    showInList: false,
    showInForm: true,
    showInFactBox: false,
  },
  {
    key: "preferred_iban",
    dbName: "preferred_iban",
    labelKey: "preferredIban",
    type: "text",
    validation: "iban",
    required: false,
    showInList: false,
    showInForm: true,
    showInFactBox: false,
  },
  {
    key: "email",
    dbName: "email",
    labelKey: "email",
    type: "text",
    validation: "emailList",
    required: false,
    showInList: true,
    showInForm: true,
    showInFactBox: false,
  },
  {
    key: "web_url",
    dbName: "web_url",
    labelKey: "websiteUrl",
    type: "text",
    validation: "containsDot",
    required: false,
    showInList: false,
    showInForm: true,
    showInFactBox: false,
  },
  {
    key: "phone",
    dbName: "phone",
    labelKey: "phone",
    type: "tel",
    validation: "digitsOnly",
    required: false,
    showInList: true,
    showInForm: true,
    showInFactBox: true,
  },
  {
    key: "address",
    dbName: "address",
    labelKey: "address",
    type: "text",
    required: false,
    showInList: false,
    showInForm: true,
    showInFactBox: false,
    formColSpan: "full",
  },
  {
    key: "city",
    dbName: "city",
    labelKey: "city",
    type: "text",
    required: false,
    showInList: true,
    showInForm: true,
    showInFactBox: false,
  },
  {
    key: "province",
    dbName: "province",
    labelKey: "province",
    type: "text",
    required: false,
    showInList: false,
    showInForm: true,
    showInFactBox: false,
  },
  {
    key: "postal_code",
    dbName: "postal_code",
    labelKey: "postalCode",
    type: "text",
    required: false,
    showInList: false,
    showInForm: true,
    showInFactBox: false,
  },
  {
    key: "country_id",
    dbName: "country_id",
    labelKey: "country",
    type: "select",
    required: true,
    relation: {
      entityKey: "countries",
      displayFieldName: "country_name",
      relationDataFieldName: "countries",
      optionValueField: "id",
      optionLabelFieldNames: ["code", "name"],
      labelSeparator: " - ",
    },
    showInList: true,
    showInForm: true,
    showInFactBox: false,
  },
  {
    key: "tax_area_id",
    dbName: "tax_area_id",
    labelKey: "taxArea",
    type: "select",
    required: false,
    relation: {
      entityKey: "taxAreas",
      displayFieldName: "tax_area_display",
      relationDataFieldName: "tax_areas",
      optionValueField: "id",
      optionLabelFieldNames: ["code"],
      navigable: true,
    },
    showInList: false,
    showInForm: true,
    showInFactBox: false,
  },
  {
    key: "portal_default_line_type",
    dbName: "portal_default_line_type",
    labelKey: "portalDefaultLineType",
    type: "option",
    required: true,
    newRowDefaultValue: "item",
    resetFieldDbNamesOnChange: ["portal_default_line_source_id"],
    options: purchaseLineTypeOptions,
    showInList: false,
    showInForm: true,
    showInFactBox: false,
  },
  {
    key: "portal_default_line_source_id",
    dbName: "portal_default_line_source_id",
    labelKey: "portalDefaultLineNo",
    type: "select",
    required: false,
    dynamicSelectOptions: {
      dependsOnDbName: "portal_default_line_type",
      source: "purchaseLineSources",
    },
    showInList: false,
    showInForm: true,
    showInFactBox: false,
  },
];

export const supplierSearchColumns = [
  "name",
  "commercial_name",
  "code",
  "tax_id",
  "email",
  "phone",
  "city",
  "province",
  "postal_code",
] as const;

export const supplierFilters: readonly EntityFilterDefinition[] = [
  {
    paramName: "name",
    column: "name",
    labelKey: "name",
    type: "text",
    operator: "ilike",
  },
  {
    paramName: "commercialName",
    column: "commercial_name",
    labelKey: "commercialName",
    type: "text",
    operator: "ilike",
  },
  {
    paramName: "code",
    column: "code",
    labelKey: "code",
    type: "text",
    operator: "ilike",
  },
  {
    paramName: "taxId",
    column: "tax_id",
    labelKey: "taxId",
    type: "text",
    operator: "ilike",
  },
  {
    paramName: "email",
    column: "email",
    labelKey: "email",
    type: "text",
    operator: "ilike",
  },
  {
    paramName: "city",
    column: "city",
    labelKey: "city",
    type: "text",
    operator: "ilike",
  },
];

export const supplierSelectColumns = [
  getDbColumnsFromFields(supplierFields, [
    "id",
    "tenant_id",
    "company_id",
    "created_at",
  ]),
  "countries(code, name)",
  "payment_channels:payment_channel_id(id, code, description)",
  "tax_areas:tax_area_id(id, code, description)",
].join(", ");

export const supplierEntity = {
  key: "suppliers",
  table: "suppliers",
  route: "/suppliers",
  labelsKey: "suppliers",
  scope: "company",
  pageMode: "list-detail",

  primaryFieldDbName: "name",
  newRoute: "/suppliers/new",

  fields: supplierFields,
  selectColumns: supplierSelectColumns,
  updatedAtColumn: "updated_at",

  searchColumns: supplierSearchColumns,
  filters: supplierFilters,

  formLayout: {
    type: "sections",
    sections: [
      {
        key: "general",
        labelKey: "sectionGeneral",
        columns: 2,
        fields: [
          { field: "name", colSpan: "full" },
          { field: "commercial_name", colSpan: "full" },
          "code",
          "tax_id",
          "country_id",
          "tax_area_id",
          "currency_code",
          "payment_channel_id",
          "withholding_rate",
          "preferred_iban",
        ],
      },
      {
        key: "addressAndContact",
        labelKey: "sectionAddressAndContact",
        columns: 2,
        fields: [
          "email",
          "phone",
          "web_url",
          { field: "address", colSpan: "full" },
          "city",
          "province",
          "postal_code",
        ],
      },
      {
        key: "supplierPortal",
        labelKey: "sectionSupplierPortal",
        columns: 2,
        fields: ["portal_default_line_type", "portal_default_line_source_id"],
      },
    ],
  },

  factBoxes: [
    {
      key: "summary",
      type: "recordSummary",
      titleLabelKey: "factBoxTitle",
    },
    {
      key: "attachments",
      type: "document",
      table: "entity_attachments",
      entityTableDbName: "entity_table",
      parentIdDbName: "record_id",

      storageProviderDbName: "storage_provider",

      supabaseBucketDbName: "storage_bucket",
      supabasePathDbName: "file_path",

      sharepointWebUrlDbName: "external_url",

      originalFileNameDbName: "file_name",
      contentTypeDbName: "mime_type",
      sizeBytesDbName: "file_size",

      orderBy: {
        column: "created_at",
        ascending: false,
      },
    },
  ],

  orderBy: {
    column: "name",
    ascending: true,
  },
} satisfies ListDetailEntityDefinition;
